// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using UtnAssistant.API.Enums;
using UtnAssistant.API.Models;

#nullable disable

namespace UtnAssistant.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927014258_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "CorrelativeType", new[] { "approved", "attended" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "CorrelativeType", "correlative_type", new[] { "approved", "attended" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ProgressStatus", new[] { "approved", "attended", "enrolled", "not_enrolled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ProgressStatus", "progress_status", new[] { "not_enrolled", "enrolled", "attended", "approved" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UtnAssistant.API.Models.Career", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Career");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.Correlative", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("IsTransient")
                        .HasColumnType("boolean")
                        .HasColumnName("isTransient");

                    b.Property<string>("RequiredSubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requiredSubjectId");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subjectId");

                    b.Property<CorrelativeType>("Type")
                        .HasColumnType("\"CorrelativeType\"")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RequiredSubjectId");

                    b.HasIndex("SubjectId", "RequiredSubjectId", "Type")
                        .IsUnique();

                    b.ToTable("Correlative");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CareerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("careerId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int?>("Credits")
                        .HasColumnType("integer")
                        .HasColumnName("credits");

                    b.Property<bool>("IsElective")
                        .HasColumnType("boolean")
                        .HasColumnName("isElective");

                    b.Property<bool>("IsIntegrator")
                        .HasColumnType("boolean")
                        .HasColumnName("isIntegrator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Semester")
                        .HasColumnType("integer")
                        .HasColumnName("semester");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CareerId", "Code")
                        .IsUnique();

                    b.HasIndex("Year", "Semester");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.SyllabusChunk", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subjectId");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("SyllabusChunk");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.UserSubjectProgress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<double?>("Grade")
                        .HasColumnType("double precision")
                        .HasColumnName("grade");

                    b.Property<ProgressStatus>("Status")
                        .HasColumnType("\"ProgressStatus\"")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subjectId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId", "SubjectId")
                        .IsUnique();

                    b.ToTable("UserSubjectProgress");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.Correlative", b =>
                {
                    b.HasOne("UtnAssistant.API.Models.Subject", "RequiredSubject")
                        .WithMany("CorrelativesAsPrereq")
                        .HasForeignKey("RequiredSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtnAssistant.API.Models.Subject", "Subject")
                        .WithMany("CorrelativesAsTarget")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequiredSubject");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.Subject", b =>
                {
                    b.HasOne("UtnAssistant.API.Models.Career", "Career")
                        .WithMany("Subjects")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Career");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.SyllabusChunk", b =>
                {
                    b.HasOne("UtnAssistant.API.Models.Subject", "Subject")
                        .WithMany("Chunks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.UserSubjectProgress", b =>
                {
                    b.HasOne("UtnAssistant.API.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtnAssistant.API.Models.User", "User")
                        .WithMany("Progress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.Career", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.Subject", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("CorrelativesAsPrereq");

                    b.Navigation("CorrelativesAsTarget");
                });

            modelBuilder.Entity("UtnAssistant.API.Models.User", b =>
                {
                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
